### ISSUE TITLE
Segmentations computed from 193 Å versus 171 Å, 211 Å versus 171 Å, and 211 Å versus 193 Å.

### ISSUE THREAD

**Issue by shibaji7** [shibaji7/CHIPS#1]
## Segmentations Computed from Different Wavelengths:

* Compute segmentations from 193 Å compared to 171 Å.
* Compute segmentations from 211 Å compared to 171 Å.
* Compute segmentations from 211 Å compared to 193 Å.
* Ensure that CHIPS is utilizing these wavelengths for its operations.

## Compute Logical Conjunction:

* Perform a logical conjunction operation on all three detection maps obtained from the above comparisons.
* Logical conjunction involves combining the detection maps such that only regions identified as coronal holes in all three maps are retained.

## Overlay and Remove Non-Coronal Hole Regions:

* Overlay the logical conjunction map obtained in the previous step with the CHIPS results.
* Remove regions from the CHIPS results that are not identified as coronal holes in the logical conjunction map.
* This step ensures that only coronal hole regions identified consistently across all wavelength comparisons are retained in the final CHIPS results.

<img width="101" alt="image" src="https://github.com/shibaji7/pyCHIPS/assets/16243802/3bacff85-b368-4798-aab5-cdc51ef7f38a">

> :warning: Create a different **Branch** for this enhancement!

**Comment by yz3259** [comment]
[like]  Tina Zhou reacted to your message:
________________________________
From: Shibaji Chakraborty ***@***.***>
Sent: Thursday, April 4, 2024 3:23:46 PM
To: shibaji7/pyCHIPS ***@***.***>
Cc: Tina Zhou ***@***.***>; Assign ***@***.***>
Subject: [shibaji7/pyCHIPS] Segmentations computed from 193 Å versus 171 Å, 211 Å versus 171 Å, and 211 Å versus 193 Å. (Issue #1)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
CAUTION:  This email came from outside of the University. To keep your account safe, only click on links and open attachments if you know the person who sent the email, or you expected to receive this communication.



Segmentations Computed from Different Wavelengths:

  *   Compute segmentations from 193 Å compared to 171 Å.
  *   Compute segmentations from 211 Å compared to 171 Å.
  *   Compute segmentations from 211 Å compared to 193 Å.
  *   Ensure that CHIPS is utilizing these wavelengths for its operations.

Compute Logical Conjunction:

  *   Perform a logical conjunction operation on all three detection maps obtained from the above comparisons.
  *   Logical conjunction involves combining the detection maps such that only regions identified as coronal holes in all three maps are retained.

Overlay and Remove Non-Coronal Hole Regions:

  *   Overlay the logical conjunction map obtained in the previous step with the CHIPS results.
  *   Remove regions from the CHIPS results that are not identified as coronal holes in the logical conjunction map.
  *   This step ensures that only coronal hole regions identified consistently across all wavelength comparisons are retained in the final CHIPS results.

image.png (view on web)<https://github.com/shibaji7/pyCHIPS/assets/16243802/3bacff85-b368-4798-aab5-cdc51ef7f38a>

⚠️ Create a different Branch for this enhancement!
